site_name: biofes
extra_javascript: 
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
markdown_extensions:
    - mdx_math
nav:
    - Home: index.md
    - Getting started: install.md
    - User Guide: guide.md
    - API Documentation: api.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - python